# Generated by Django 4.0.4 on 2022-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_mvt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatives',
            name='family_relationship',
            field=models.CharField(default='Familiar', max_length=255),
        ),
    ]
