# Generated by Django 4.0.4 on 2022-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_mvt_app', '0003_relatives_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
