# Generated by Django 4.0.4 on 2022-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_mvt_app', '0004_alter_relatives_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatives',
            name='image',
        ),
    ]
